<?php

namespace LEM_projet2\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CivilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CivilityRepository extends EntityRepository
{
}
