# app/config/security.yml

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        LEM_projet2\AdminBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            entity: { class: LEM_projet2\AdminBundle\Entity\User, property: email }

    firewalls:
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path:  /login
                check_path:  /login_check
                # options de redirection lorsque le login a réussi (vous
                # pouvez en lire plus ci-dessous)
                always_use_default_target_path: false
                default_target_path:            /home
                target_path_parameter:          _target_path
                use_referer:                    false
            logout:
                path:   /logout
                target: /home
                
#        admin:
#            pattern: ^/admin
#            anonymous: false
#            provider: main
#            form_login:
#                login_path:  /admin_login
#                check_path:  /admin_login_check
#                # options de redirection lorsque le login a réussi (vous
#                # pouvez en lire plus ci-dessous)
#                always_use_default_target_path: false
#                default_target_path:            /admin
#                target_path_parameter:          _target_path
#                use_referer:                    false
#            logout:
#                path:   /logout
#                target: /home
           
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }        
#        - { path: ^/admin_login, roles: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/client, roles: ROLE_USER }
